/**
 * Content generators for tool-registry.ts, README tool sections, and manifest.json.
 */

import path from "node:path";
import type { LineTool } from "../../src/tooling/lineTool.js";
import type { CollectedField } from "./collect-fields.js";

export type ToolEntry = { file: string; tool: LineTool };

/** Derive a JS import name from a file path: broadcastFlexMessage.ts → broadcastFlexMessage */
function toolImportName(file: string): string {
  return path.basename(file, ".ts");
}

/** Build the contents of src/generated/tool-registry.ts. */
export function buildRegistryContent(toolEntries: ToolEntry[]): string {
  const imports = toolEntries
    .map(({ file }) => {
      const name = toolImportName(file);
      const baseName = path.basename(file, ".ts");
      return `import ${name} from "../tools/${baseName}.js";`;
    })
    .join("\n");

  const entries = toolEntries
    .map(({ file }) => `  ${toolImportName(file)},`)
    .join("\n");

  return `/* AUTO-GENERATED BY scripts/sync-tool-artifacts.ts */
/* DO NOT EDIT DIRECTLY. */

import type { LineTool } from "../tooling/lineTool.js";
${imports ? `\n${imports}\n` : ""}
export const TOOL_REGISTRY: readonly LineTool[] = [
${entries}
];
`;
}

/** Render a numbered markdown list of tools for a README. */
export function renderToolsMarkdown(
  tools: LineTool[],
  toolFields: Map<string, CollectedField[]>,
  locale: "en" | "ja",
): string {
  const inputLabel = locale === "en" ? "Inputs" : "入力";
  const noneLabel = locale === "en" ? "None" : "なし";

  return tools
    .map((tool, index) => {
      const num = `${index + 1}`;
      const indent = " ".repeat(num.length + 2);
      const summary = tool.summary[locale];
      const fields = toolFields.get(tool.name) ?? [];
      const fieldsSection =
        fields.length === 0
          ? `${indent}- **${inputLabel}:** ${noneLabel}`
          : [
              `${indent}- **${inputLabel}:**`,
              ...fields.map(
                field =>
                  `${indent}  - \`${field.path}\` (${field.type}): ${field.description[locale]}`,
              ),
            ].join("\n");

      return `${num}. **${tool.name}**
${indent}- ${summary}
${fieldsSection}`;
    })
    .join("\n\n");
}

/** Build updated manifest.json tools array. */
export function buildManifestTools(
  tools: LineTool[],
): { name: string; description: string }[] {
  return tools.map(tool => ({
    name: tool.name,
    description: tool.summary.en,
  }));
}
