name: "Reminder for 'run npm audit'"

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  run-npm-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    if: github.repository == 'line/line-bot-mcp-server'
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: '24'

      - name: Run npm audit and check diff
        id: audit
        run: .github/scripts/npm-audit.sh
        continue-on-error: true

      - name: Create or update reminder issue
        if: steps.audit.outcome == 'failure'
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        env:
          TZ: 'Asia/Tokyo'
        with:
          script: |
            const { owner, repo } = context.repo;
            const title = 'Reminder: run npm audit';
            const securityURL = `https://github.com/${owner}/${repo}/security`;
            const baseBody = [
              'Fix all vulnerabilities. You can check with `.github/scripts/npm-audit.sh` locally, then send a PR with the fixes.',
              `After fixing, make sure the vulnerabilities count in **${securityURL}** is **0**.`
            ].join('\n\n');

            const { data: result } = await github.rest.search.issuesAndPullRequests({
              q: `repo:${owner}/${repo} is:issue is:open in:title "${title}"`
            });

            const today = new Date();

            if (result.total_count === 0) {
              await github.rest.issues.create({
                owner,
                repo,
                title,
                body: `${baseBody}\n\n0 days have passed.`
              });
            } else {
              const issue = result.items[0];
              const created = new Date(issue.created_at);
              const diffDays = Math.floor((today - created) / 86_400_000);
              await github.rest.issues.update({
                owner,
                repo,
                issue_number: issue.number,
                body: `${baseBody}\n\n${diffDays} days have passed.`
              });
            }
